// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (Entry, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	UpdateAccounts(ctx context.Context, arg UpdateAccountsParams) error
	UpdateEntries(ctx context.Context, arg UpdateEntriesParams) error
}

var _ Querier = (*Queries)(nil)
